# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            mdoradom
tagline:          'Portfolio'
description:      'Creating games. Based in Barcelona. Pro FOSS ðŸ’™'
url:              /
baseurl:          /mdoradom/

author:
  name:           'mdoradom'
  url:            https://github.com/mdoradom/

paginate:         5

# Custom vars
version:          0.5.8

download:
  cv:             /assets/mario_dorado_martinez_cv.pdf

github:
  repo:           https://github.com/mdoradom/mdoradom

plugins:
  - jekyll-paginate
  - gemoji
  - jekyll-seo-tag
  - jekyll-sitemap
